name: Update stars
on:
  schedule:
    - cron: '30 5 * * 3'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          python -m pip install -U pip
          python -m pip install aiohttp
          python .github/workflows/update_stars.py ${{ secrets.GITHUB_TOKEN }}
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Update stars"
            git push origin main
          fi
